// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application";

import CalendarController from "./calendar_controller";
application.register("calendar", CalendarController);

import CheckController from "./check_controller";
application.register("check", CheckController);

import FlatpickrController from "./flatpickr_controller";
application.register("flatpickr", FlatpickrController);

import HamburgerController from "./hamburger_controller";
application.register("hamburger", HamburgerController);

import HoldseatController from "./holdseat_controller";
application.register("holdseat", HoldseatController);

import LeaveController from "./leave_controller";
application.register("leave", LeaveController);

import NotificationController from "./notification_controller";
application.register("notification", NotificationController);

import OpentimeController from "./opentime_controller";
application.register("opentime", OpentimeController);

import OrdertimeController from "./ordertime_controller";
application.register("ordertime", OrdertimeController);

import TablemapController from "./tablemap_controller";
application.register("tablemap", TablemapController);
